"""fix job_executions

Revision ID: e035122a26d7
Revises: 79814c2d7265
Create Date: 2026-01-05 21:30:23.703574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e035122a26d7'
down_revision: Union[str, Sequence[str], None] = '79814c2d7265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_executions', sa.Column('error_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_executions', 'error_message')
    # ### end Alembic commands ###
